import { Link } from 'react-router-dom';

function Home() {
  return (
    <>
      <header className="hero fade-in">
        <h1>Welcome to ALITHEA.AI</h1>
        <p>
          The ultimate platform for detecting AI-generated content. Choose a service below to verify whether an image or text was created by an artificial intelligence model.
        </p>
      </header>
      <main className="fade-in" style={{ display: 'flex', gap: '2rem', justifyContent: 'center', flexWrap: 'wrap', padding: '2rem 1rem' }}>
        <div className="card" style={{ flex: '1', minWidth: '300px', display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center' }}>
          <h2>🖼️ Image Detector</h2>
          <p style={{ marginBottom: '2rem', marginTop: '1rem', color: 'var(--text-light)' }}>
            Upload an image to verify if it was generated by AI or if it's a real photograph. Our CNN model analyzes subtle pixel artifacts.
          </p>
          <Link to="/image-detection" className="btn-primary" style={{ textDecoration: 'none' }}>Go to Image Detector</Link>
        </div>

        <div className="card" style={{ flex: '1', minWidth: '300px', display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center' }}>
          <h2>📝 Text Detector</h2>
          <p style={{ marginBottom: '2rem', marginTop: '1rem', color: 'var(--text-light)' }}>
            Paste any text to determine if it was written by a human or generated by an LLM like ChatGPT using NLP techniques.
          </p>
          <Link to="/text-detection" className="btn-primary" style={{ textDecoration: 'none' }}>Go to Text Detector</Link>
        </div>
      </main>
    </>
  );
}

export default Home;
